### ISSUE TITLE
Windows ISF editor: Small text size when running 4K

### ISSUE THREAD

**Issue by mjoergensencph** [mrRay/VVISF-GL#2]
When using the Windows ISF beta on a 4K monitor the text size of the source code, is very very small. I can't seem to be able to increase the text size anywhere. Otherwise thanks for porting to Windows!

**Comment by mrRay** [comment]
thanks, this is fixed in commit 2787443f88ab2eadc35b7434702f4c6863869a5c.  if you run the auto-updater in the help menu of the installed app it'll grab 2.9.8, which has this change in it
