### ISSUE TITLE
Network Error 99

### ISSUE THREAD

**Issue by SadlerJohnson** [mrRay/VVISF-GL#3]
Currently using ISF Editor Windows beta 2.9.11.0.  I have a "Network Error 99" consistently. What does 99 mean, assuming its not a catch-all network error. Get it when importing from ShaderToy but not from GL Sandbox.

**Comment by mrRay** [comment]
according to Qt's documentation, 99 means "an unknown network-related error was detected", which sounds like a catch-all network error.  it doesn't appear to be a global issue with shadertoy support, i just used 2.9.11.0 to import several ISFs from both GLSLSandbox and shadertoy without issue.

what steps have you taken to try to narrow down the source of the problem?  have you restarted anything?  is it a specific composition (or combination of composition) import(s) that's causing problems for you?

**Comment by SadlerJohnson** [comment]
Hello Ray, thanks for replying,

I tried firewall settings. I've tried different local networks connected to the web. I've tried running it in Administrator mode. I've tried WireShark and there's no packets sent for ShaderToy - there are packets sent for GL Sandbox. If I type garbage in the URL field for ShaderToy the Network 99 error is shown. If I type garbage in the GL Sandbox URL field I get "cannot parse URL" message.

It is all ShaderToys that fail- it seems it isn't getting as far as the website (which I can access fine through a browser and tracert). I seem to remember, perhaps an older version of ISF Editor worked but I can't find an older version to test.

**Comment by mrRay** [comment]
okay, i think i see what's going on.  the only real difference between those builds is the vsn of the base Qt libs that i compiled them against (no changes were made to any network code between them).  the latest version of qt changed which version of OpenSSL it links against, and the version included in this project is now "too old".

if you're hell-bent on using the latest version of the ISF editor (and are comfortable mucking around with things like this), downloading OpenSSL 1.1.1 and placing the 64-bit dlls in the same directory as the ISF editor will let you work around this until i put together another release.

**Comment by SadlerJohnson** [comment]
Not hell-bent but might test it to check if that's a fix.  Thanks for all your help.

**Comment by Clyde-L** [comment]
Currently having this issue as well.  Running on 2 different computers both the current download version.  Hoping to see a fix for this.
